// Assemble docs/plan/30-plan-scorecard.md from the six group scorecards.
const fs = require('fs');
const path = require('path');
// Paths resolve from this file, so the script runs from any checkout on Windows or Linux.
const SP = path.join(__dirname, 'parts') + path.sep;
const OUT = path.join(__dirname, '..', '..', 'docs', 'plan', '30-plan-scorecard.md');
const AXES = ['Completeness', 'Consistency', 'Feasibility', 'Risk honesty', 'Testability', 'Distinctiveness', 'Portability'];
const G = ['A', 'B', 'C', 'D', 'E', 'F'];
const scores = {};
const bodies = {};
for (const g of G) {
  const t = fs.readFileSync(SP + 'score-' + g + '.md', 'utf8').replace(/\r/g, '');
  bodies[g] = t.replace(/^#### Group [A-F]\s*\n/, '').trim();
  scores[g] = {};
  for (const a of AXES) {
    const m = new RegExp('^\\| ' + a + ' \\| (\\d)', 'm').exec(t);
    if (!m) throw new Error(g + ' missing ' + a);
    scores[g][a] = Number(m[1]);
  }
}
const L = [];
const p = (x = '') => L.push(x);
const date = new Date().toISOString().slice(0, 10);
p('# 30. Plan Scorecard');
p();
p('## Purpose');
p();
p('This document records how good the plan is, group by group, against the seven-axis rubric in `PLAN_SPEC.md` ("The scorecard"), with quoted evidence for every score. **A group is approved only at 4 or better on every axis; an average never substitutes for a low score.** It exists so the product owner approves the plan on evidence, and so the remaining work before approval is a named, sized list rather than a feeling.');
p();
p('## Scope');
p();
p('| In scope | Owned elsewhere |');
p('|---|---|');
p('| Scores for Groups A to F with evidence, the verdict per group, the gaps and the shortest path to approval | The rubric: `PLAN_SPEC.md`; the procedure: `/score-plan` and `docs/templates/scorecard.md` |');
p('| The consolidated remediation plan across groups | The brief corrections themselves: ADR-0019 and the v9.1 briefs |');
p('| | Document 30 does not score itself, and document 00 is scored after it is written |');
p();
p('## Content');
p();
p('### 1. Method');
p();
p('Each group was scored by an independent reviewer instructed to be adversarial, to quote the document with file and line for every score, and to reserve 5 for work that needs no change. Every reviewer was given the same established facts: `kit-lint` is clean including rule R19 (every cited identifier exists in its catalog); document 03 holds 860 requirements; document 34 builds 858 of them in 718 slices and explains the other 2; document 20 gives every requirement a test identifier. The reviewers were then asked to find what tooling cannot: contradictions of meaning, thin sections, unowned unknowns, claims with no test. The four most consequential findings were re-checked by hand before this document was written (Section 4).');
p();
p('### 2. Summary');
p();
p('| Group | ' + AXES.join(' | ') + ' | Lowest | Verdict |');
p('|---|' + AXES.map(() => '---|').join('') + '---|---|');
for (const g of G) {
  const v = AXES.map((a) => scores[g][a]);
  const blocked = AXES.filter((a) => scores[g][a] < 4);
  p('| ' + g + ' | ' + v.join(' | ') + ' | ' + Math.min(...v) + ' | ' + (blocked.length ? 'Blocked (' + blocked.length + ' axes)' : 'Approved') + ' |');
}
const axisMin = AXES.map((a) => Math.min(...G.map((g) => scores[g][a])));
p('| **Lowest per axis** | ' + axisMin.map((x) => '**' + x + '**').join(' | ') + ' | | |');
p();
p('**Verdict: no group is approved yet.** Portability is the one axis at 4 or better almost everywhere. The plan is complete in coverage (every requirement is specified, built by a slice and tested) but not yet consistent in meaning, and its schedule does not match its own work breakdown. Every gap below is sized; none requires rethinking the architecture.');
p();
p('### 3. Scores by group');
p();
const names = { A: 'Understanding (01, 02; 00 last)', B: 'Requirements and architecture (03, 04, 05, 07)', C: 'Services, data, messaging, performance (06, 10, 11, 21)', D: 'Web, mobile, security, workflows, design (08, 09, 12, 13, 14)', E: 'Operations, testing, roadmap, risk, dependencies, traceability (15 to 20)', F: 'Conventions to work breakdown (22 to 29, 31 to 34)' };
let n = 1;
for (const g of G) {
  p('#### 3.' + n++ + ' Group ' + g + ': ' + names[g]);
  p();
  p(bodies[g]);
  p();
}
p('### 4. Findings re-checked by hand');
p();
p('| Finding | Checked against | Result |');
p('|---|---|---|');
p('| Document 02 says seven of ten competitors publish an API | `02-competitive-gap-analysis.md` lines 69, 96, 119 and its matrix | Confirmed: the text says seven, the matrix supports six |');
p('| The Gateway cannot read the revoked-user mark, so a signed-out leaver keeps a working token | `06-services/identity.md` open point 13 and `21-performance-engineering.md` Section 2.3 | Confirmed: Identity writes `state:revoked:`, document 21 grants `svc_gateway` no read on it |');
p('| Every load gate depends on k6, which the dependency inventory does not allow | `19-dependency-and-license-inventory.md` line 224 | Confirmed: k6 2.3.0, AGPL-3.0, "not-allowed until a Section 6.4 row and ADR exist" |');
p('| Phase 1 is 423 slice-days against a roadmap range of 8 to 10 weeks | Master brief Section 29 team shape (two to four backend, one to two web, one mobile, one quality engineer) and document 34 Section 2 | Confirmed: 423 × 1.3 / (5 to 8 builders × 5 days) is 14 to 22 weeks |');
p('| Documents 10 and 21 name the AI index `embeddings`; document 25 names `embedding_chunk` | `10-data-architecture.md` line 266 | Confirmed |');
p();
p('### 5. What blocks approval, across groups');
p();
p('The group gap lists overlap. Consolidated, the work before approval is eight themes, in the order they should be done because later ones depend on earlier ones.');
p();
p('| # | Theme | Groups | What closes it | Effort |');
p('|---|---|---|---|---|');
p('| 1 | **Product-owner decisions** | A, B, D, E, F | Absence-alert timing; public API, OneRoster and iCal in Tier 1; target countries, Apple build capacity and certifications. Each is recorded in `OPEN_QUESTIONS.md`, document 01 and a RISK row in document 18 until answered | 1 hour of the owner\'s time; 3 hours to record |');
p('| 2 | **Schedule matches the work breakdown** | E, F | Re-range every phase in document 17 from document 34\'s slice-days at the Section 29 team shape, recompute the MVP line, and state the team size each range assumes | 1 day |');
p('| 3 | **Brief corrections (v9.1)** | all | ADR-0019 applies the logged appendix defects (`tools/plan-build/parts/brief-findings.md`): missing events, permissions and error codes, the k6 Section 6.4 row, the proposed CAP-INT-02 and CAP-INT-03 in the roadmap, the conflicting values (cooling-off, invitation expiry, dedupe window), JOD decimals, Appendix W\'s autonomy column | 3 days |');
p('| 4 | **One meaning per fact across plan documents** | A to F | Fix the named contradictions: the synchronous-call graph in 04, 05 and 07; `embedding_chunk` in 10 and 21; the Gateway\'s Redis reads in 21; the permission-refresh owner in 08, 11 and 12; OneRoster\'s and WF-INF-01\'s phase; webhooks\' tier; Finance\'s numeric precision; the API count in 02 and 32 | 3 days |');
p('| 5 | **One test-identifier registry** | A, B, D, E, F | Make document 16 the registry of every `TC-` identifier, resolve the collisions (TC-PLT-001 to 005, TC-DOC-002), register the locally minted ones, and add a kit-lint rule that every cited `TC-` identifier is registered exactly once | 2 to 3 days |');
p('| 6 | **Verification claims that run** | A, D, E, F | Every "How this document is verified" row either names a check that exists or is restated as a review step; the missing kit-lint rules worth having are built (open questions compared with document 01, risk-table arithmetic) | 2 days |');
p('| 7 | **Risk honesty everywhere** | A to F | Every Open point carries likelihood and a RISK identifier; documents without an Open points or risk section get one (03, 08, 09, 10, 11, 12, 14, 21, 29, 33); document 18 re-scored (RISK-03, RISK-07, RISK-34) and extended (AI, k6, pending decisions, the brief backlog) | 1.5 days |');
p('| 8 | **Every signature feature proven on the stage** | A, C, E, F | The 23 of 44 features without a release-gated demo step get one in Appendix O and document 32; feature 39 gets its proof; the phase 2 demo minutes that cannot run as scripted are re-scripted | 1.5 days |');
p();
p('**Total: about 14 to 15 working days of plan work**, plus the product owner\'s decisions. Themes 2, 4, 5 and 6 lift Consistency, Feasibility and Testability, the three lowest axes.');
p();
p('### 6. Re-score');
p();
p('Each group is re-scored with `/score-plan` after the themes that touch it are closed, and the new scores replace Section 2 with the old ones kept in the review record. The plan is approved when every group is at 4 or better on every axis, and document 00 is then written and scored last.');
p();
p('## Decisions in force');
p();
p('| Decision | Record |');
p('|---|---|');
p('| Approve only at 4 or better on every axis | `PLAN_SPEC.md`, "The scorecard" |');
p('| Scores need quoted evidence; a score without evidence is not a score | `.claude/commands/score-plan.md` |');
p('| Brief defects are corrected together under one ADR and a version bump | CLAUDE.md working rules; ADR-0019 (to be written) |');
p();
p('## Dependencies on other documents');
p();
p('| Document | What this one takes |');
p('|---|---|');
p('| `PLAN_SPEC.md` | The rubric and the approval rule |');
p('| Every plan document in Groups A to F | The evidence |');
p('| `34-work-breakdown.md` | The slice-days behind the feasibility scores |');
p('| `20-traceability-matrix.md` | The test coverage behind the testability scores |');
p();
p('## Open points');
p();
p('| Point | Default | Owner |');
p('|---|---|---|');
p('| The three product-owner decisions in Section 5 theme 1 | The plan follows the requirement as written until decided | Product owner |');
p('| Whether to build or restate the missing kit-lint checks (theme 6) | Build the two with the most leverage, restate the rest as review steps | Architect |');
p();
p('## Review record');
p();
p('| Date | Reviewer | Result |');
p('|---|---|---|');
p('| ' + date + ' | Six independent adversarial reviewers, one per group; four findings re-checked by hand | Groups A to F blocked; lowest axes Consistency (' + axisMin[1] + ') and Feasibility (' + axisMin[2] + '); remediation of about 14 to 15 days in eight themes |');
p();
p('## How this document is verified');
p();
p('| Claim | Proof |');
p('|---|---|');
p('| Every score has evidence | Each row of Section 3 quotes a document with file and line; a row without one is invalid |');
p('| The summary table matches the group scores | Section 2 is computed from Section 3 by the assembly script, not typed |');
p('| The most consequential findings are real | Section 4 records the hand check of each |');
p('| The verdict follows the rule | A group with any axis below 4 is shown blocked; the script applies the rule |');
p();
fs.writeFileSync(OUT, L.join('\n'), 'utf8');
console.log('written; mins per axis', axisMin.join(','));
